theme: jekyll-theme-minimal
title: JuyoungIt's page

# Site Author
author:
name: "JuyoungIt"
avatar: "/image/Ryan.jpeg"
bio: "한동대학교 전산전자공학부 컴퓨터공학심화 2학년"
location: "Pohang, South Korea"
email: "htj3460@gmail.com"
